FROM php:7.4-apache
#FROM php:7.4.0-fpm-alpine
COPY . /var/www/html/
RUN apt update -y
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN service apache2 restart
RUN docker-php-ext-install mysqli
EXPOSE 80
